Решенa задачa 2-3 #16
Bodichane/programming pull request #17
Opened 2022-10-06 10:03 UTC by Bodichane

2022-10-06 12:37 UTC, MarinaPaley reviewed
Contitnue
👍

2022-10-06 14:54 UTC, MarinaPaley requested changes

2022-10-06 14:54 UTC, MarinaPaley commented on Task 2/Task 2-3/main.cpp
> +double getSide(const string& message)
не используется

2022-10-06 14:54 UTC, MarinaPaley commented on Task 2/Task 2-3/main.cpp
> +double const getTime1(const double v1, const double s1)
Одна функция для расчет времени

2022-10-06 14:54 UTC, MarinaPaley commented on Task 2/Task 2-3/main.cpp
> +        const double T = half * (getTime1(v1, s1) + getTime2(v2, s2) + getTime3(v3, s3));
В функцию `sum(...)`

2022-10-06 16:43 UTC, Bodichane commented on Task 2/Task 2-3/main.cpp
> +double getSide(const string& message)
Я уже использовал функцию getSide()

2022-10-10 16:06 UTC, MarinaPaley approved these changes

2022-10-10 18:06 UTC, merged